site_name: PyMdown 扩展文档
site_url: https://wohugb.github.io/pymdown-extensions
repo_url: https://github.com/wohugb/pymdown-extensions
edit_uri: tree/master/docs/src/markdown
site_description: Python Markdown的有用扩展的集合
copyright: |
  版权 &copy; 2014 - 2018 <a href="https://github.com/facelessuser">艾萨克·穆</a>
  <br><span class="md-footer-custom-text">表情符号免费提供</span><a href="http://www.emojione.com">EmojiOne</a>

docs_dir: docs/src/markdown
theme:
  name: material
  language: zh
  custom_dir: docs/theme
  palette:
    primary: blue
    accent: blue
  logo:
    icon: description
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "\ue157"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:

extra:
  search:
    language: 'jp'
  social:
    - type: github
      link: https://github.com/wohugb/pymdown-extensions
    - type: globe
      link: http://wohugb.github.io
    - type: github-alt
      link: https://github.com/wohugb
    - type: twitter
      link: https://twitter.com/wohugb
    - type: linkedin
      link: https://linkedin.com/in/wohugb
extra_css:
  - extra-4e53a56959.css
extra_javascript:
  - extra-d8800ea088.js

pages:
  - 简介: index.md
  - 安装: installation.md
  - 使用说明: usage_notes.md
  - 扩展:
    - Arithmatex(数学公式): extensions/arithmatex.md
    - B64(图片BASE64): extensions/b64.md
    - BetterEm(加粗斜体增强): extensions/betterem.md
    - Caret(上标): extensions/caret.md
    - Critic(评论家): extensions/critic.md
    - Details(细节): extensions/details.md
    - Emoji(表情): extensions/emoji.md
    - EscapeAll(转义): extensions/escapeall.md
    - Extra(扩展): extensions/extra.md
    - ExtraRawHTML(html): extensions/extrarawhtml.md
    - GitHub: extensions/github.md
    - Highlight(高亮): extensions/highlight.md
    - InlineHilite(行内高亮): extensions/inlinehilite.md
    - Keys(按键): extensions/keys.md
    - MagicLink(魔术链接): extensions/magiclink.md
    - Mark(做记号): extensions/mark.md
    - PathConverter(路径转换): extensions/pathconverter.md
    - StripHTML(转义html): extensions/striphtml.md
    - ProgressBar(进度条): extensions/progressbar.md
    - SmartSymbols(智能符号): extensions/smartsymbols.md
    - Snippets(片段): extensions/snippets.md
    - SuperFences(超级栅栏): extensions/superfences.md
    - Tasklist(任务列表): extensions/tasklist.md
    - Tilde(波浪号): extensions/tilde.md
  - 其他附加: miscellaneous_extras.md
  - 贡献 &amp; 支持: contributing.md
  - 发展: development.md
  - 更新日志: changelog.md
  - 许可: license.md

